---
title: "Coefficient Tables"
author: "Lio, Orestis"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    toc : true
    toc_float : true
editor_options: 
  chunk_output_type: console
  
---

<style>
p.caption {
  font-size: 0.9em;
  font-style: italic;
  color: grey;
  margin-right: 10%;
  margin-left: 10%;  
  text-align: center;
}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)

library("tidyverse")
library("lubridate")

knitr::opts_chunk$set(echo = FALSE)
rm(list = ls())

source("ImportLong.r")

df2<-df%>%
  dplyr::select(all_of(c(basic,GoogleVars,behavioural,covid,economy,Policy)))



#C1_School.closing:H1_Public.information.campaigns

```

```{r}

cr<-df2%>%
  filter(!is.na(StringencyIndex),!is.na(Movement))%>%
  group_by(Country)%>%
  mutate(cor_simple=cor.test(StringencyIndex,Movement)$estimate[[1]],
    coef_simple=summary(lm(Movement~StringencyIndex))$coefficients[2,1],
            se_simple=summary(lm(Movement~StringencyIndex))$coefficients[2,2])

```

```{r}
df3<-cr%>%
  filter(!is.na(LTO))%>%
  group_by(Country)%>%
  summarise_all(first)%>%
  dplyr::select_if(is.numeric)%>%
  dplyr::select(COL:se_simple)%>%
  dplyr::select(-StringencyIndex)

c<-cor(df3,use="pairwise.complete.obs")


lto<-df%>%
  filter(!is.na(StringencyIndex),!is.na(Movement),!is.na(LTO))%>%
  group_by(Country)%>%
  mutate(cor_simple=cor.test(StringencyIndex,Movement)$estimate[[1]])%>%
  summarise(LongTerm=mean(LTO),Cor=mean(cor_simple))%>%
   mutate(Country = forcats::fct_reorder(Country, LongTerm))
  



#cor.test(lto$LongTerm,lto$Cor)  

```


